apiVersion: apps/v1
kind: Deployment
metadata:
  name: heathcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: bhargavdocker1/healthcare-project-bhargav:1
        ports:
        - containerPort: 8084

---
apiVersion: apps/v1
kind: Service
metadata:
  name: heathcare
spec:
  selector:
      app: healthcare
    type: NodePort
    ports:
        - Port: 80
          targetPort: 8084
          nodePort: 30007
